title: Li Wan's homepage
page-top-title: Li Wan
# top-section-bg-text: Be what you wanna be
home-subtitle: Wan Li &ensp;|&ensp;天津大学 硕士研究生
copyright-text: '&copy; Yourname 2024-2027. All Rights Reserved.'
